version: "3.3"
services:
  db:
    image: postgres:12
    restart: always
    networks:
      - default
    ports:
      - "5432:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
      - .env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  backend:
    image: "${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}"
    restart: always
    depends_on:
      - db
    ports:
      - "8888:8888"
    networks:
      - default
    env_file:
      - .env
      - .env.local
    environment:
      - PORT=8888
      - DB_TYPE=postgres
    volumes:
      - ~/.openastra:/root/.openastra
    build:
      context: backend

  frontend:
    image: "${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}"
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.local
    networks:
      - default
    environment:
      - PORT=3000
    build:
      context: frontend
      args:
        - NODE_ENV=local
volumes:
  app-db-data:
