name: Feedback
description: Provide feedback or report an issue for OpenAstra
title: '[Feedback] '
labels: ['feedback']
body:
  - type: checkboxes
    id: feedback_type
    attributes:
      label: Type of Feedback
      description: Please check one of the following
      options:
        - label: Bug Report
        - label: Feature Request
        - label: General Feedback
        - label: Question

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of your feedback
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: If reporting a bug, describe what you expected to happen

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: If reporting a bug, describe what actually happened

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (if applicable)
      description: If reporting a bug, provide steps to reproduce the issue
      placeholder: |
        1.
        2.
        3.

  - type: input
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your feedback
      placeholder: Add a link to your screenshot

  - type: input
    id: environment
    attributes:
      label: Environment (if applicable)
      description: Provide details about your environment
      placeholder: |
        - Browser: [e.g. Chrome, Safari]
        - OS: [e.g. Windows, MacOS]
        - Version: [e.g. 22]

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about your feedback here
